name: CI/CD Workflow

# Triggers
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# que hacer
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Instalar dependencias
        run: npm install
      
      - name: Lint del código
        run: npm run lint
      
      - name: Ejecutar pruebas
        run: npm test

      - name: Simular despliegue
        run: | echo "Despliegue simulado: La aplicación paso lint y pruebas correctamente."